import os
import numpy as np
import unittest

from layer import *
from data.datamnist import *
from functional import *
from network import Network


"""
This test class was partially generated by GPT 4.1.

Following is the prompt that was given to the GPT to sense check if the neural network 
is performing the dot products and other computations correctly. 

Imagine a neural network with 1 input 1 hidden and 
1 output layer. 

Do not apply any activation functions on
these layers 
- Input layer will have two neurons 
- Hidden layer will have 3 neurons with following weights [2,6],[4,2],[1,9] 
- Output layer will have 2 neurons with following weights [1,3,3],[4,2,6] 

If input is [2,3] what would be the output of the feed forward?

"""


class TestForward(unittest.TestCase):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.init_weights()
        self.init_bias()
        self.network_mock = Network(
            'unit',
            [
                Layer(neurons=3, activation=mock),  # hidden layer without activation
                Layer(neurons=2, type="output", activation=mock)  # output layer without activation
            ],
            False
        )
        self.network_with_activations = Network(
            'unit',
            [
                Layer(neurons=3, activation=relu),  # hidden layer without activation
                Layer(neurons=2, type="output", activation=softmax)  # output layer without activation
            ],
            False
        )
        self.input_data = np.array([[2, 3]])

    def init_weights(self):
        os.makedirs("data/weights", exist_ok=True)
        if not os.path.isfile("data/weights/unit.npz"):
            np.savez(
                "data/weights/unit.npz",
                np.array([[2, 6], [4, 2], [1, 9]], dtype=float),  # hidden layer weights
                np.array([[1, 3, 3], [4, 2, 6]], dtype=float)    # output layer weights
            )

    def init_bias(self):
        os.makedirs("data/bias", exist_ok=True)
        if not os.path.isfile("data/bias/unit.npz"):
            np.savez(
                "data/bias/unit.npz",
                np.zeros(3),  # hidden layer bias
                np.zeros(2)   # output layer bias
            )

    def test_forward_pass(self):
        # Validates if the feed forward is working correctly without the activation functions.
        output = self.network_mock.forward_pass(self.input_data) 
        expected_output = np.array([151, 290])
        
		# Validates if the feed forward is working correctly with the activation functions.
        softmax_output = np.round(self.network_with_activations.forward_pass(self.input_data)) 
        softmax_expected = np.array([0, 1])

        np.testing.assert_array_equal(output, expected_output)
        np.testing.assert_array_equal(softmax_output, softmax_expected)

    """
    Tests backpropogation for cross entropy. 
	These weights are manually calculated and computations are validated using LLM (GPT4.1).
    """
    def test_backpropogation(self):
        self.network_with_activations.train(self.input_data, [0,1], number_of_classes=2)
        reversed_layers = list(reversed(self.network_with_activations.layers))
        for index, layer in enumerate(reversed_layers):
            if layer.type == 'output':
                expected_output_weights = np.array([[1.022, 3.014, 3.029],[3.978, 1.986, 5.971]])
                np.testing.assert_array_equal(layer.weights, expected_output_weights)
            else:
                expected_hidden_weights = np.array([[1.994088, 5.991132],[4.002056, 2.003084],[0.994116, 8.991174]])
                np.testing.assert_array_equal(layer.weights, expected_hidden_weights)


if __name__ == '__main__':
    unittest.main()
